# using conda with Azure DevOps: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=ubuntu-16-04

trigger:
- main

jobs:
  - job: windows
    pool:
      vmImage: windows-latest
    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH

      - script: |
          conda create -p ./venv python=3.6.5 -y
          source activate ./venv
          conda install requests pytorch torchvision cudatoolkit=10.2 -c pytorch -y
          conda install -c sdvillal openslide 
          pip install -e .
        displayName: 'Install dependencies'
  
  # - job: macOS
  #   pool:
  #     vmImage: macOS-latest
  #   steps:
  #     - bash: echo "##vso[task.prependpath]$CONDA/bin"
  #       displayName: Add conda to PATH

  # - job: linux
  #   pool:
  #     vmImage: ubuntu-latest
  #   steps:
  #     - bash: echo "##vso[task.prependpath]$CONDA/bin"
  #       displayName: Add conda to PATH


# - script: |
#     pytest
#   displayName: 'Run tests'
