[tool.black]
include = 'gandlf_*'
extend-exclude = '''
/(
  testing/data
  | .*.md
)/
'''

[tool.coverage.run]
source = ["./GANDLF"]
omit = [
  "./setup.py",
  "./GANDLF/anonymize/slide_anonymizer.py",
  "./testing/conftest.py",
  "./gandlf_*",
  ".github/*",
  ".devcontainer/*",
]
