# affix version
version:
  {
    minimum: 0.0.6,
    maximum: 0.0.6 # this should NOT be made a variable, but should be tested after every tag is created
  }
# the dimension of the model and dataset: defines dimensionality of computations
dimension: 3
# Choose the model parameters here
model:
  {
    # dimension = 3
    # base_filters
    # other model-related properties can go here
    architecture: resunet, # options: unet, resunet, fcn, uinc
    final_layer: None # can be either sigmoid, softmax or none (none == regression)
  }
# Set base filters: number of filters present in the initial module of the U-Net convolution; for IncU-Net, keep this divisible by 4
base_filters: 16
# Set the Modality : rad for radiology, path for histopathology
modality: rad
# Set the list of labels the model should train on and predict
class_list: [0,1,2,4]
# Patch size during training - 2D patch for breast images since third dimension is not patched 
patch_size: [128,128,128]
# Set the batch size
batch_size: 1
# Set if you want to use Automatic Mixed Precision for your operations or not - options: True, False
amp: False
