theme: jekyll-theme-cayman
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Installation
    url: setup
  - title: Usage
    url: usage
  - title: Extending GaNDLF
    url: extending
  - title: Acknowledgements
    url: acknowledgements
