steps:
- script: |
    conda create -p ./venv python=3.7 -y
    source activate ./venv
    pip install -e .
    conda install requests pytorch torchvision torchaudio cpuonly -c pytorch -y
    conda install -c sdvillal openslide -y 
    conda install -c conda-forge libvips -y
    pip install numpy==1.19.2
  displayName: 'Install dependencies'

- script: |
    source activate ./venv
    python -c "import numpy as np;print(np.__version__)"
    python -c "import torch as t;print(t.__version__)"
    python -c "import torchio as tio;print(tio.__version__)"    
  displayName: 'Testing versions'
  
- script: |
    source activate ./venv
    pytest
  displayName: 'Run Tests'
