name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Debug
        run: |
          python -c "import os; print(os.getcwd()); import sys; print(sys.path)"
      - name: Extract black version from setup.py
        run: |
          echo "BLACK_VERSION=$(python -c 'from setup import black_version; print(black_version)')" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          version: ${{ env.BLACK_VERSION }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==${{ env.BLACK_VERSION }}
      
      - name: Run tests
        run: |
          python -m black --check .
