# This workflow will test gandlf deploy for model and metrics MLCubes

name: MLCube-Test

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      call-reusable-workflow:
        uses: ./.github/workflows/dependencies.yml
        with:
          node-version: '14'

      - name: Run mlcube deploy tests
        working-directory: ./testing
        if: steps.changed-files-specific.outputs.only_modified == 'false' # Run on any non-docs change
        run: |
          sh test_deploy.sh
